=== klacol/IfcDiesUndDas/SampleSchemas/IfcWallStandardCase.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "IfcWallStandardCase",
	"title": "IfcWallStandardCase",
	"description": "Schema for objects of the type \"IfcWallStandardCase\"",
	"type": "object",
	"properties": {
		"GlobalId": {
			"description": "The unique id of the wall in the UUID notation according to IETF RFC 4122, e.g 123e4567-e89b-12d3-a456-426655440000",
			"type": "string",
			"maxLength": 36,
			"nullable": true
		},
		"Name": {
			"description": "The name of the wall",
			"type": "string",
			"maxLength": 255,
			"nullable": true
		},
		"Description": {
			"description": "The Description of the wall",
			"type": "string",
			"maxLength": 3000,
			"nullable": true
		},
		"LateBindedDataTemplate": {
		  "description": "Definition of a data template that can be lately binded to the schema. The late binded properties are not part of the core specification",
		  "$ref": "MyGreatDataTemplate.schema.json"
		}
	},
	"required": [
		"GlobalId",
		"Name"
	]
}

=== klacol/IfcDiesUndDas/SampleFiles/IfcWallStandardCase.json
{
	"GlobalId": "fc844dd2-f71a-4a85-8010-8cd7154504a7",
	"Name": "Wall xyz",
	"Description": "Description of Wall",
	"LateBindedDataTemplate": {
		"Volume": 181698.20138837994,
		"Combustible": false,
		"ThermalTransmittance": 0.24,
		"IsExternal": true,
		"ExtendToStructure": false,
		"LoadBearing": false,
		"Compartmentation": false
	}
}
